### PR TITLE
NMCLI-Simplified Commit

### PR DESCRIPTION
**Pull request by TheAnonymousCrusher**
This project, ```NMCLI-Simplified```, is a tool created to simplify the process of managing network connections in a Linux system using nmcli. It provides a set of aliases that make the syntax more intuitive and user-friendly. The aliases include nmcon for connecting to a network, nmdis for disconnecting from a network, nmstat for displaying the status of all network devices, and nmlist for showing a list of all established network connections. The project is particularly useful in window manager environments like sway or dwm, which typically lack a user interface for network connections.

### CODE REVIEW

**Comment by thom311** [comment]
The right place for merge requests for NetworkManager is https://gitlab.freedesktop.org/NetworkManager/NetworkManager . This github repository is only a read-only fork. Please report there. Closing here.

Also, all contributions to NM should be LGPL-2.1-or-later licensed, and use SPDX-Licence identifiers.

Also, using sudo doesn't seem best. Usually, configure policykit so that your user has permissions (or pass `nmcli --ask` to elevate permissions).

I personally don't see the simplification by providing bash aliases. I mean, everybody can configure aliases however they like, but to define a standard set of aliases, seems not general enough.

**Comment by TheAnonymousCrusher** [comment]
Hi @thom311,

Thanks for your feedback on `NMCLI-Simplified`. I appreciate your insights and are committed to improving the project. I'll transition from aliases to a more comprehensive solution, incorporating best practices like `policykit` for permissions and `nmcli --ask` for elevation. I'll also consider adding a dedicated tool or script for better network management.

I'm hopeful that the improved project will be accepted into the official `NetworkManager ` repository (on Gitlab obviously) and look forward to your continued support.

Regards, @TheAnonymousCrusher

**Comment by thom311** [comment]
see how there is `/usr/bin/nmtui-connect`, which is a symlink to `nmtui`.

Then `nmtui` is called, it checks it's `g_get_prgname()`, and if that is for example `nmtui-connect`, then it behaves differently...

Not saying that should be done, but maybe that could be used alternatively to adding convenience aliases.

**Comment by TheAnonymousCrusher** [comment]
Dear @thom311 ,

I would like to express my sincere gratitude for your continued support and guidance in refining this idea. Your insights and expertise have been invaluable in this process, and I am confident that they will continue to be as this project moves forward.

At the moment, I am occupied with other projects, which have temporarily diverted my attention from `NMCLI Simplified`. However, I have my sights set to resuming work on this project as soon as these other commitments are resolved.

Thank you once again for your understanding and support. I look forward to your continued insights on `NMCLI Simplified`.

Best regards,
@TheAnonymousCrusher

**Pull request closed without merging**
