### PR TITLE
lr/wwan-ppp-route-rh1585611:  wwan: set the route parameters at the beginning of ip4 config 

### PR DESCRIPTION
**Pull request by lkundrak**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1585611

### CODE REVIEW

**Comment by lkundrak** [comment]
Actually, not. Let's do that in stage2, so that it works for both IPv4 and IPv6.

**Comment by thom311** [comment]
nm_modem_set_route_parameters_from_device() takes the device's route-metric and route-table.

Note, that reapply does not permit changes to route-table setting ( https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/devices/nm-device.c?id=c2932dd7dbb8997b7c46b49506efbd16cd3f56ca#n10399 ), however, it allows to reapply changes to the route-metric.

By calling it only in state2, I think reapplying the route-metric won't work with routes obtained from NMModem, will it? Usually, during reapply we restart DHCP/autoconf6, so we use the new route-metric.

**Comment by bengal** [comment]
LGTM

**Comment by bengal** [comment]
> Usually, during reapply we restart DHCP/autoconf6, so we use the new route-metric.

Do we? I think not. Currently, route-metrics don't seem to be reapplied for DHCP. That is a missing feature.

**Comment by thom311** [comment]
ah, it doesn't work for the default-route, but works for DHCP.

Missing feature is ok, but then https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/devices/nm-device.c?id=c2932dd7dbb8997b7c46b49506efbd16cd3f56ca#n10399 should reject reapplying the route-metric.

**Pull request merged**
