### PR TITLE
contrib: add a serial modem emulator

### PR DESCRIPTION
**Pull request by lkundrak**
Useful for quickly testing the ModemManager integration.

### CODE REVIEW

**Comment by thom311** [comment]
Nice. But it's really not clear to me how to use this for testing? The comments explain the arguments, and what it does. But not how to use it exactly. Can you give examples how one would use this?

**Comment by lkundrak** [comment]
I don't precisely now what you mean -- just run it.
Also, there's an EXAMPLES section in the manual?

**Comment by thom311** [comment]
I see now. OK

**Comment by bengal** [comment]
Hi,
I tried the script and it fails with:

```
Can't send a netlink message: Connection refused at contrib/test/modemu.pl line 116.
Can't send a netlink message: Connection refused at contrib/test/modemu.pl line 116.
END failed--call queue aborted.
```
Any idea why?

**Comment by lkundrak** [comment]
Merged.

**Pull request closed without merging**
