### PR TITLE
th/ifcfg_simple_dbus

### PR DESCRIPTION
**Pull request by thom311**

### CODE REVIEW

**Comment by vhumpa** [comment]
Heya Thomas, please disregard the 'default' check result, I've just created a trigger for pull requests here and it isn't yet finished coding. Disabled that until done. It's good to see the triggering works though.

**Comment by vhumpa** [comment]
rebuild

**Comment by vhumpa** [comment]
rebuild

**Comment by vhumpa** [comment]
rebuild

**Comment by thom311** [comment]
arguably, I ended up not using `NM_UNCONST_PTR()` and `NM_UNCONST_PPTR()`, and they are only in an intermediate step. That was, because originally I wanted to do it that way, but later I change it further.

It's still keep these commits, because `NM_UNCONST_PTR()` does something I find (unfortunately) lacking in C: a form of C++'s const_cast<>().

**Comment by thom311** [comment]
@bengal better now?

**Comment by thom311** [comment]
merged to master

**Pull request closed without merging**
