### PR TITLE
WIP: implement 'mode vti' for ip tunnels

### PR DESCRIPTION
**Pull request by oxpa**
Hello.

I'm trying to implement VTI tunnels for linux.
If you are curious 'why do I need those': I have multiple ipsec tunnels and it's convenient to have separate VTI tunnels to manage traffic using routing tables.

At this point I can create a connection with a command like:
`nmcli c add save yes type ip-tunnel con-name ipsectest ifname testvti remote 10.0.0.1 mode vti`
And faced a couple of troubles:
* ~~I don't know how to implement CLI options like `key`, `okey`, `ikey`~~
* I don't know how to force device removal when a connection is removed

Could anyone please help me figuring out where to start ?

Thanks !

### CODE REVIEW

**Comment by vhumpa** [comment]
NM CI: Please confirm test execution over this PR. Comment .*ok\W+to\W+test.* to confirm and/or .*add\W+to\W+whitelist.* to add the PR author in whitelist for future.

**Comment by oxpa** [comment]
ok to test

**Comment by oxpa** [comment]
I'll work on parsing options and get back with a better pull request.

**Comment by thom311** [comment]
is this useful without xfrm support? What would it take to also configure that?

Also, for a larger work (like this), please open a merge request at https://gitlab.freedesktop.org/NetworkManager/NetworkManager/merge_requests .

**Comment by oxpa** [comment]
I'm afraid xfrm will require much more work than VTI. And is way too new for me to have a practical reason to implement. I'll give it a try if I'm able to complete VTI support.

I'd be happy though if you could point me to any relevant docs. It looks like I'm doing something wrong as I can't make NM add IP address onto VTI device/connection.

**Pull request closed without merging**
