### PR TITLE
th/ipv6_ll_reapply_rh1552069

### PR DESCRIPTION
**Pull request by thom311**
Attempt to fix handling of IPv6 LL address, especially in light of reapply.

This shall fix test `ipv6_route_set_route_with_tables_reapply`

See also https://bugzilla.redhat.com/show_bug.cgi?id=1552069

### CODE REVIEW

**Comment by bengal** [comment]
LGTM up to "device: cleanup completing wait for linklocal6" included.

The rest of the branch seems unrelated to the first part and perhaps should be a separate branch / PR?

**Comment by thom311** [comment]
> The rest of the branch seems unrelated to the first part and perhaps should be a separate branch / PR?
Ok. The remainder of the branch depends on the previous part. I see no point in rebasing it first down to master, and later resolve the conflict again. I dropped these commits for now, will open a second PR later.

How about the current state?

**Comment by thom311** [comment]
Ok, this branch contains much too many commits. I split it now and repushed.

Current HEAD of the pull request is `th/ipv6-ll-reapply-rh1552069`. This contains mostly refactoring and uncontroverse(?) changes. Let's see that with this branch CI still does as well as it does on master.

The remainder will be resurrected later, on top of this branch.

Please review the current state, and if we agree, merge it soon to master.

**Comment by bengal** [comment]
Ack.

**Comment by thom311** [comment]
Merged the branch with refactorings as commit 217a7ad55ad4d09f2c195930ba548d46d660ed24

The remainder will be handled by follow-up #80.

**Pull request closed without merging**
