### PR TITLE
docs: misc. typos pt2

### PR DESCRIPTION
**Pull request by luzpaz**
Remainder of typos found using `codespell -q 3 --skip="./shared,./src/systemd,*.po" -I ../NetworkManager-word-whitelist.txt` whereby whitelist consists of:  
 ```
ans
busses
cace
cna
conexant
crasher
iff
liftime
creat
nd
sav
technik
uint
```

### CODE REVIEW

**Comment by vhumpa** [comment]
NM CI: Please confirm test execution over this PR. Comment .*ok\W+to\W+test.* to confirm and/or .*add\W+to\W+whitelist.* to add the PR author in whitelist for future.

**Comment by thom311** [comment]
Merged to master.

Thanks!!

**Comment by thom311** [comment]
hey @luzpaz. You contributed two patches to NetworkManager, and thereby some of the files were GPL2.0+ licensed. We are collecting agreement of the copyright holders on NetworkManager's GPL code, to relicense it under LGPL-2.1+. See ([1])

[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/master/RELICENSE.md.

Would you give your agreement to that? If yes, could you please give a clear indication that you do agree, for example, simply be replying to this thread, and clearly expressing your thoughts? (or, if you have questions, we can discuss that too).

This is especially relevant due to https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/390#note_500824.

Your patches may be few, but I would prefer to just get your OK, instead of making such a judgement call myself.

Thank you.

**Comment by luzpaz** [comment]
@thom311 Sorry I missed this. I consent

**Pull request closed without merging**
