### PR TITLE
[th/platform-netlink-cleanup]

### PR DESCRIPTION
**Pull request by thom311**
Some cleanup of platform's netlink code.

### CODE REVIEW

**Comment by vbenes** [comment]
a crash here:
https://faf.lab.eng.brq.redhat.com/faf//reports/10667/

**Comment by thom311** [comment]
> a crash here:
> https://faf.lab.eng.brq.redhat.com/faf//reports/10667/

This bug is also on master, not related to this branch.

An [assertion](https://github.com/NetworkManager/NetworkManager/blob/fc9d6610182bf205587bf8c6b87c4333bc0c6e43/src/devices/wifi/nm-device-wifi-p2p.c#L974) in Wi-Fi P2P failed.

**Comment by benzea** [comment]
The Wi-Fi P2P crash should be fixed by https://gitlab.freedesktop.org/NetworkManager/NetworkManager/merge_requests/85

**Comment by bengal** [comment]
lgtm

**Comment by thom311** [comment]
thanks. Merged to master

**Pull request closed without merging**
