### PR TITLE
th/platform_route_pt4

### PR DESCRIPTION
**Pull request by thom311**
more patches reworking route handling.

The last patch reworks handling of the default route. It's complicated.

All earlier patches are trivial and just preparation. I'd like to merge them early, they are simple enough, please ACK that part first.

### CODE REVIEW

**Comment by bengal** [comment]
LGTM up to (including) "core: add nm_utils_connection_has_default_route()".

**Comment by bengal** [comment]
With commit "_core: rework handling of default-routes and drop NMDefaultRouteManager_" I see duplicated routes:

```
  default via 192.168.122.1 dev ens9 proto static metric 100
  default via 192.168.10.30 dev ens3 proto static metric 100
  default via 192.168.122.1 dev ens9 proto static metric 20100
  default via 192.168.10.30 dev ens3 proto static metric 20100

```

**Comment by thom311** [comment]
I merged a large set of the branch as [a214f398e7b17cacad335f70462a606affc2ad63](https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=a214f398e7b17cacad335f70462a606affc2ad63).

This contains patches in preparation of dropping NMDefaultRouteManager.

The remainder is still up for review.

**Comment by thom311** [comment]
Ok, all merged as 4bc231e33abb4f5edb6fc1f42053a06e6e5fd5ec


A few tests are still failing:

Two tests seem wrong now. They stop NetworkManager and expect NM to take over after restart. But these are externally configured devices, so, they need more checking:
- renewal_gw_after_dhcp_outage_for_assumed_var1
- persistent_default_ipv6_gw

4 Tests fail for unknown reason:
- show_zones_after_firewalld_install
- connectivity_check
- disable_connectivity_check
- reload_dns

3 other failures are under control, the just need adjustment of the test because of intentional change.

**Pull request merged**
