### PR TITLE
cli: fix string matching

### PR DESCRIPTION
**Pull request by bengal**

### CODE REVIEW

**Comment by thom311** [comment]
the "expected" files must also be dist-ed in Makefile.am. That is rather inconvenient indeed... maybe that should be changed, that the tests only work from git...

**Comment by bengal** [comment]
> the "expected" files must also be dist-ed in Makefile.am. That is rather inconvenient indeed... maybe that should be changed, that the tests only work from

Fixed, thanks.

**Comment by thom311** [comment]
lgtm

**Comment by lkundrak** [comment]
looks good (though a rebase & conflict resolution is needed before merge)

**Comment by bengal** [comment]
Merged.

**Pull request closed without merging**
