### PR TITLE
th/dhcp_client_id_bgo790660

### PR DESCRIPTION
**Pull request by thom311**
Extend `ipv4.dhcp-client-id` to use the MAC address of the current device.

Also, make the property configurable via global default.
For example with a file `/etc/NetworkManager/conf.d/30-dhcp-client-id.conf`:

```
[connection-30-dhcp-client-id]
ipv4.dhcp-client-id=mac
```

Addresses: https://bugzilla.gnome.org/show_bug.cgi?id=790660

### CODE REVIEW

**Comment by thom311** [comment]
Note that `"mac"` and `"perm-mac"` generates a `01:xx` client id, while `"stable"` generates one with `00:...`. I think that makes sense, does it?

**Comment by bengal** [comment]
LGTM

**Comment by thom311** [comment]
Thanks. Merged to master.

**Comment by freakynl** [comment]
Initial tests here are looking great. Boot file is attached. It's a somewhat modified version of
dnf --installroot=/some/path --releasever=27 group install 'LXDE Desktop' 
as initrd (/etc/machine-id cleared, /etc/fstab added, selinux disabled) with the RPM's I build from the pull request sources installed over the original ones.

Log shows it reading the suggested config file (in NetworkManager.conf under main dhcp=internal was also set) and getting an IP. On the DHCP server side I can see the MAC address as ID.

[log.txt](https://github.com/NetworkManager/NetworkManager/files/1740696/log.txt)

Thanks a lot :).

**Pull request closed without merging**
